name: PHP Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1' # Escolha a versão do PHP que você deseja

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php -r "if (hash_file('sha384', 'composer-setup.php') === 'HASH-DO-COMPOSER') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
        mv composer.phar /usr/local/bin/composer
      working-directory: ${{ github.workspace }}

    - name: Install dependencies
      run: composer install
      working-directory: ${{ github.workspace }}

    - name: Start PHP server
      run: php -S 0.0.0.0:8080 -t public/
      working-directory: ${{ github.workspace }}
