name: PHP Composer

on:
  push:
    branches:
      - main # Substitua pelo nome de sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4 # Escolha a versão do PHP que você precisa

    - name: Install Composer
      run: |
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php
        php -r "unlink('composer-setup.php');"
        mv composer.phar /usr/local/bin/composer

    - name: Install PHP dependencies
      run: composer install

    # Aqui você pode adicionar etapas adicionais, como implantar seu aplicativo ou fazer outras tarefas necessárias.
